elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"

logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash:/etc/logstash/conf.d
  ports:
    - "8080:8080"
  links:
    - elasticsearch
    
kibana:
  image: kibana:latest
  ports:
    - "5601:5601"
  links:
    - elasticsearch